import SideBar from "./components/sideBar/sideBar"
import './global.css';
export const metadata = {
  title: 'Omar   Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <SideBar content={children} />




      </body>
    </html>
  )
}
